version: 2
jobs:
  build:
    working_directory: ~/code
    containerInfo:
    - image: maven:3.3.9-jdk-8
      cmd: ["/bin/bash"]
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx1500m
    steps:
      - checkout
      - run:
          name: make keystore folder
          command: mkdir -p keystore
      - run:
          name: decode keystore
          command: echo ${ENCODED_KEYSTORE} | base64 --decode > keystore/lady_happy_key_store.jks
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Copy google-services.json
          command: echo ${GOOGLE_SERVICES} | base64 --decode > app/google-services.json
      - run:
          name: test
          command: cat app/google-services.json
      - run:
          name: make debug folder
          command: mkdir -p app/src/debug
      - run:
          name: Copy debug google-services.json
          command: echo ${GOOGLE_SERVICES} | base64 --decode > app/src/debug/google-services.json
      - run:
          name: make release folder
          command: mkdir -p app/src/release
      - run:
          name: Copy release google-services.json
          command: echo ${GOOGLE_SERVICES} | base64 --decode > app/src/release/google-services.json
      - run:
          name: Download Dependencies
          command: |
                  sudo chmod +x gradlew
                  ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: |
                  sudo chmod +x gradlew
                  ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/